[package]
name = "appchain-anchor"
version = "0.1.0"
authors = ["Octopus Network"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.1.0"

[dev-dependencies]
near-sdk = "3.1.0"
near-sdk-sim = "3.1.0"
hex = "0.4.2"
num-format = "0.4.0"
# remember to include related mock contracts
mock-appchain-registry = { path = "../mock-appchain-registry" }
mock-oct-token = { path = "../mock-oct-token" }
mock-wrapped-appchain-token = { path = "../mock-wrapped-appchain-token" }
